name: deploy lambda function
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      REPOSITORY_NAME: aws-lambda

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: config aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: install node_modules
        run: npm install
        
      - name: zip Lambda Function
        run: zip -r9 lambda_function.zip *
        
      - name: update code
        run: aws lambda update-function-code --function-name lambda_function --zip-file fileb://lambda_function.zip
